name: Benchmark

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    benchmark:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 22
              uses: actions/setup-node@v4
              with:
                  node-version: 22.14.0
            - name: Use node_modules cache
              uses: actions/cache@v4
              with:
                  path: node_modules
                  key: yarn-node-22-lock-${{ hashFiles('yarn.lock') }}
                  restore-keys: |
                      yarn-node-22-lock-
            - run: yarn install --frozen-lockfile
            - name: Run benchmark
              uses: CodSpeedHQ/action@v3
              with:
                  token: ${{ secrets.CODSPEED_TOKEN }}
                  run: yarn bench
